<a href="https://colab.research.google.com/github/parvesh7o7/Data-Science-Learning/blob/main/movies_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# http://www.omdbapi.com/?i=tt3896198&apikey=4a4589fe

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
movies_data = pd.read_csv('bollywood_box_clean.csv')

In [16]:
movies_data.head()

,movie_name,movie_opening,movie_weekend,movie_firstweek,movie_total,movie_total_worldwide,movie_genre,movie_director,release_date,release_day,release_month,release_year,runtime,producer,banner,actors,movie_details
0,Angrezi Medium,4.03,9.03,9.36,9.36,13.50,"Drama, Comedy",Homi Adajania,"13 March, 2020",13,Mar,2020,145,"Dinesh Vijan , Jyoti Deshpande","Maddock Films, Jio Studios","Irrfan Khan , Radhika Madan, Kareena Kapoor",When his daughter decides to further her studi...
1,Baaghi 3,17.50,53.83,90.67,93.37,137.00,Action,Ahmed Khan,"06 March, 2020",6,Mar,2020,147,Sajid Nadiadwala,"Nadiadwala Grandson Entertainment, Fox Star S...","Tiger Shroff , Shraddha Kapoor, Riteish Deshmukh",A man embarks on a bloody rampage to save his ...
2,Thappad,3.07,14.66,22.79,30.61,44.50,"Drama, Social",Anubhav Sinha,"28 February, 2020",28,Feb,2020,142,"Bhushan Kumar , Krishan Kumar, Anubhav Sinha","Benaras Media Works, T-Series Super Cassettes...","Taapsee Pannu , Pavail Gulati, Dia Mirza",Thappad is a story of Amrita whose seemingly p...
3,Shubh Mangal Zyada Saavdhan,9.55,32.66,44.84,62.78,86.39,"Comedy, Romance",Hitesh Kewalya,"21 February, 2020",21,Feb,2020,120,"Aanand L Rai , Himanshu Sharma, Bhushan Kumar","Colour Yellow Productions Pvt Ltd, T-Series S...","Ayushman Khurana , Jitendra Kumar, Gajraj Rao",The road to achieving a happy ending is a litt...
4,Bhoot: Part One - The Haunted Ship,5.10,16.36,24.18,31.97,40.94,Horror,Bhanu Pratap Singh,"21 February, 2020",21,Feb,2020,117,"Hiroo Johar , Karan Johar, Apoorva Mehta","Dharma Productions, Zee Studios","Vicky Kaushal , Bhumi Pednekar, Ashutosh Rana",A couple is trapped on an abandoned ship lying...

In [17]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movie_name             130 non-null    object
 1   movie_opening          130 non-null    float64
 2   movie_weekend          130 non-null    float64
 3   movie_firstweek        130 non-null    float64
 4   movie_total            130 non-null    float64
 5   movie_total_worldwide  130 non-null    float64
 6   movie_genre            129 non-null    object
 7   movie_director         130 non-null    object
 8   release_date           130 non-null    object
 9   release_day            130 non-null    int64
 10  release_month          130 non-null    object
 11  release_year           130 non-null    int64
 12  runtime                130 non-null    int64
 13  producer               129 non-null    object
 14  banner                 130 non-null    object
 15  actors                 126 non-null    object
 16  movie_details          119 non-null    object
dtypes: float64(5), int64(3), object(9)
memory usage: 17.4+ KB

In [18]:
movies_data[movies_data['movie_genre'].isnull()]

,movie_name,movie_opening,movie_weekend,movie_firstweek,movie_total,movie_total_worldwide,movie_genre,movie_director,release_date,release_day,release_month,release_year,runtime,producer,banner,actors,movie_details
83,Gold,25.25,71.3,89.3,107.37,149.5,NaN,Reema Kagti,"15 August, 2018",15,Aug,2018,153,"Ritesh Sidhwani , Farhan Akhtar",Excel Entertainment,"Akshay Kumar , Mouni Roy, Kunal Kapoor","Set in 1948, the historic story of India's fir..."

In [27]:
movies_data[movies_data['movie_genre'].isnull()]

,movie_name,movie_opening,movie_weekend,movie_firstweek,movie_total,movie_total_worldwide,movie_genre,movie_director,release_date,release_day,release_month,release_year,runtime,producer,banner,actors,movie_details
83,Gold,25.25,71.3,89.3,107.37,149.5,NaN,Reema Kagti,"15 August, 2018",15,Aug,2018,153,"Ritesh Sidhwani , Farhan Akhtar",Excel Entertainment,"Akshay Kumar , Mouni Roy, Kunal Kapoor","Set in 1948, the historic story of India's fir..."

### **DROPPING THE NULL ROW OF THE MOVIE_GENRE COLUMN**

---

In [28]:
movies_data.dropna(subset=['movie_genre'], inplace=True)

In [30]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129 entries, 0 to 129
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   movie_name             129 non-null    object
 1   movie_opening          129 non-null    float64
 2   movie_weekend          129 non-null    float64
 3   movie_firstweek        129 non-null    float64
 4   movie_total            129 non-null    float64
 5   movie_total_worldwide  129 non-null    float64
 6   movie_genre            129 non-null    object
 7   movie_director         129 non-null    object
 8   release_date           129 non-null    object
 9   release_day            129 non-null    int64
 10  release_month          129 non-null    object
 11  release_year           129 non-null    int64
 12  runtime                129 non-null    int64
 13  producer               128 non-null    object
 14  banner                 129 non-null    object
 15  actors                 125 non-null    object
 16  movie_details          118 non-null    object
dtypes: float64(5), int64(3), object(9)
memory usage: 18.1+ KB

### **UNIQUE MOVIE_GENRE AVAILABLE IN DATA**

---

In [35]:
unique_genres = movies_data['movie_genre'].unique()
print("//////Movie Genre///////\n")
print(unique_genres, "\n")
print("Total Genre: ", len(unique_genres))

//////Movie Genre///////

['Drama, Comedy' 'Action' 'Drama, Social' 'Comedy, Romance' 'Horror'
 'Romance' 'Romance, Action' 'Drama, Romance' 'Comedy, Drama'
 'Sports, Drama' 'Dance' 'Historical, Action' 'Drama' 'Comedy'
 'Crime, Action, Thriller' 'Historical, war, Action'
 'Action, Romance, Drama' 'Biographical' 'Action, Thriller'
 'Romance, Drama' 'Action, Crime, Thriller' 'Action, Romance, Comedy'
 'Comedy, Crime, Thriller' 'Crime, Thriller' 'Thriller' 'Drama, Period'
 'Drama, Romance, Action' 'Period, Drama, Romance'
 'Drama, Period, Mystery, Thriller' 'Spy, Action, Thriller'
 'Period, Action, war' 'Crime, Action' 'Musical' 'Action, Comedy, Drama'
 'Action, Drama' 'Sci-fi, Action' 'Comedy, Action' 'Drama, Thriller'
 'Action, Adventure' 'Crime, Drama' 'Horror, Thriller'
 'Thriller, Suspense, Crime' 'Comedy, Horror' 'Biographical, Sports'
 'Drama, Social, Thriller' 'Action, Romance' 'Social'
 'Historical, Drama, Action' 'Drama, Sports' 'Drama, Musical'
 'Biographical, Crime']

Total Genre:  51